### PR TITLE
Subships revised

### PR DESCRIPTION
**Pull request by fustilio**
implemented subships as a spritegroup, similar to how OP made the enemiesgroup

### CODE REVIEW

**Comment by leerob** [comment]
Just out of curiosity, what are you building with this?

**Comment by fustilio** [comment]
Hi leerob,

Our team used your space invaders program as a base to create an even more modern twist of space invaders, with quantum computing!

You can take a look here: https://github.com/HuangJunye/QPong, for the original inspiration of quantum games. In QPong, a quantum circuit composer is used to control the position of the paddle.

We decided to create another quantum arcade game linked here: https://github.com/fustilio/Space_Invaders

Running the game requires the setup of Qiskit too as we are using their libraries to simulate quantum behaviours.

image
Quantum Circuit Composer

image
Ships in a state of superposition

We'll write a readme in the near future describing how to actually play it. But briefly, you can play the game normally using buttons O and P to move left and right and space bar to shoot. To open and close the quantum circuit composer, press Enter. To move around in the quantum circuit composer, use W,A,S,D and try some of the quantum gates available X and H are the easiest to understand.

**Comment by ktnc985** [comment]
To add on to what @fustilio said, we made this as part of the the IBM Qiskit hackathon that was held in Singapore over the weekend, you can find our initial write up [here](https://github.com/qiskit-community/qiskit-hackathon-singapore-19/issues/26)

**Comment by leerob** [comment]
That's awesome - great work!

**Pull request closed without merging**
